In [52]:
import numpy as np

### Basics

In [53]:
#Making a 1D Array
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [54]:
#2D Array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [55]:
#Get Dimensions
print(a.ndim)
print(b.ndim)

1
2


In [56]:
#Get Shape
print(a.shape) #3 elements
print(b.shape) #2 Rows, 3 Columns


(3,)
(2, 3)


In [57]:
#Get Type
print(a.dtype)
print(b.dtype)

int32
int64


In [58]:
#Get Size
print(a.itemsize) #32 bits is 4 bytes
print(b.itemsize) #64 bits is 8 bytes

4
8


In [59]:
#Get total size
print(a.size*a.itemsize) # 3 elements of 4 bytes
print(b.size*b.itemsize) # 6 elements of 8 bytes

# OR
print(a.nbytes)
print(b.nbytes)

12
48
12
48


### Accessing/Changing specific elements,rows,columns,etc

In [61]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [62]:
a.shape #2R 7C

(2, 7)

In [66]:
#Get a specific element
print(a[0][1]) #1st Row & 2nd column (2)
#OR
print(a[0,1])

2
2


In [67]:
#Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [68]:
#Get a specific column
a[:,5]

array([ 6, 13])

In [70]:
#Fancy boi
a[0,1:7] #1st row and columns 2 to 6

array([2, 3, 4, 5, 6, 7])

In [73]:
#even more fancy
a[1,1:6:2] #1st Row and colums from 2 to 5, skipping 2 elements

array([ 9, 11, 13])

In [80]:
a[1,6] = 20
print(a)

a[1,:] = 3
a

[[ 1  2  3  4  5  2  7]
 [ 2  2  2  2  2  2 20]]


array([[1, 2, 3, 4, 5, 2, 7],
       [3, 3, 3, 3, 3, 3, 3]])

#### 3D Example

In [82]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [95]:
# Get a specific element (Work outside in)

#Let's say we want '7'
b[1,1,0]

np.int64(7)

### Initializing Diff Types of Arrays

In [97]:
# All Zeroes Matrix
np.zeros((2,3)) # 2R 3C of 0's

array([[0., 0., 0.],
       [0., 0., 0.]])

In [98]:
#All Ones Matrix

np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [99]:
# Any other number
np.full((3,4),99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

In [100]:
#Random decimal numbers
np.random.rand(4,2)

array([[0.51988027, 0.35514626],
       [0.37075196, 0.4539726 ],
       [0.06248572, 0.35189342],
       [0.65474924, 0.05202102]])

In [104]:
#Random integer numbers
np.random.randint(0,5,size=(3,3)) #Lower bound, Upper bound, size

array([[2, 0, 4],
       [3, 1, 2],
       [3, 3, 2]])

In [105]:
#Identity Matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [119]:
# Repeat
arr = np.array([[1,2,3,4]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3 4]
 [1 2 3 4]]


In [127]:
output = np.ones((5,5))


z = np.zeros((3,3))
z[1,1] = 9


output[1:4,1:4] = z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Copying Arrays

In [131]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)
print(b)
#a also got changed

[100   2   3]
[100   2   3]


In [134]:
a = np.array([1,2,3])
b = a.copy() #OR 
c = np.copy(a)
b[0] = 100
c[1] = 200
print(a)
print(b)
print(c)

[1 2 3]
[100   2   3]
[  1 200   3]


### Mathematics

In [136]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [137]:
a+2

array([3, 4, 5, 6])

In [138]:
a-2

array([-1,  0,  1,  2])

In [139]:
a**2

array([ 1,  4,  9, 16])

In [140]:
a*2

array([2, 4, 6, 8])

In [141]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [145]:
b = np.array([1,4,5,3.14])
a+b

array([2.  , 6.  , 8.  , 7.14])

In [143]:
# Take cosine
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [146]:
#Take sine
np.sin(b)

array([ 0.84147098, -0.7568025 , -0.95892427,  0.00159265])

### Linear Algebra

In [147]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [148]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [151]:
# Finding determinant
c = np.identity(3)
ans = np.linalg.det(c)
print(ans)

1.0


### Statistics

In [152]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [155]:
ans = np.min(stats)
print(ans)

1


In [157]:
answer = np.max(stats)
print(answer)

6


In [158]:
print(np.sum(stats))

21


### Reorganizing Arrays

In [159]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [163]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [166]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
output = np.vstack([v1,v2,v1,v2])
print(output)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [170]:
# Horizontally stacking vectors

h1 = np.ones((2,4))
h2 = np.zeros((2,2))
output = np.hstack([h1,h2])
print(output)

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


### Miscellaneous

#### Load Data from file